[project]
name = "nofn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "ccxt>=4.5.17",
    "chromadb>=1.3.5",
    "hyperliquid-python-sdk>=0.20.1",
    "langchain>=1.0.5",
    "langchain-anthropic>=1.1.0",
    "langchain-chroma>=1.0.0",
    "langchain-core>=1.0.4",
    "langchain-openai>=1.0.2",
    "loguru>=0.7.3",
    "numpy>=2.3.4",
    "psutil>=7.1.3",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "termcolor>=3.2.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.14.3",
]
